syntax = "proto3";

package bmd.cloud.api.file.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "bmd_cloud_api_user_v1_types.proto";

option java_package = "com.blackmagicdesign.android.cloud.protobuf";

enum Permission {
	PERMISSION_UNSPECIFIED = 0;
	PERMISSION_READ = 1;
	PERMISSION_DOWNLOAD = 2;
	PERMISSION_MODIFY = 3;
	PERMISSION_CREATE = 4;
	PERMISSION_DELETE = 5;
	PERMISSION_SHARE = 6;
}

// Attribute key must be <= 255 bytes
message Attribute {
	oneof attr {
		// A String value must be <= 1KB
		string string = 1;
		uint32 uint32 = 2;
		int32 int32 = 3;
		uint64 uint64 = 4;
		int64 int64 = 5;
		double double = 6;
		google.protobuf.Timestamp timestamp = 7;
		bool bool = 8;
		string file = 9;
		// deletion marker used to unset an attribute
		google.protobuf.Empty delete = 10;
		// Only set by the service not the client.
		// The target to upload a file attribute to.
		string pending_file = 11;
		bytes bytes = 12;
	}
}

message PermissionList {
	repeated Permission permissions = 1;
}

message Policy {
	// The volume the user is requesting access to
	string volume_id = 1;

	// The paths and permission rules that make up the policy
	map<string, PermissionList> permissions = 2;
}

message VolumeInfo {
	// Pool the volume belongs to
	string pool_name = 1;

	// Unique identifier of the volume
	string volume_id = 2;

	// Root inode of the volume
	string root_inode_id = 3;

	// root inode of the trash bin
	string trash_inode_id = 4;

	// The user owns the volume
	bmd.cloud.api.user.v1.User owner = 5;

	// The level of access granted to the current user
	Policy policy = 6;

	// Size of the files/attributes on the volume in bytes
	uint64 size = 7;
}

enum INodeType {
	I_NODE_TYPE_UNSPECIFIED = 0;
	I_NODE_TYPE_DIR = 1;
	I_NODE_TYPE_FILE = 2;
	I_NODE_TYPE_FORK = 3;
}

message SHA256 {
	bytes data = 1;
}

message INodeInfo {
	// Unique identifier of the volume
	string volume_id = 1;

	// Unique identifier of the file/directory
	string inode_id = 2;

	// inode type - file or directory
	INodeType type = 3;

	// full pathname
	string path = 4;

	// optional field. Only set if the type == file
	// Version of the file whose details are in this response
	uint32 version = 5;

	// optional field. Only set if type == file
	uint64 size = 6;

	// optional field. Only set if type == file
	uint32 chunk_size = 7;

	// optional fields.
	// timestamps the file or directory was created/modified at
	google.protobuf.Timestamp client_created_at = 8;
	google.protobuf.Timestamp client_modified_at = 9;
	google.protobuf.Timestamp server_created_at = 10;
	google.protobuf.Timestamp server_modified_at = 11;

	// optional field.
	// custom attributes
	map<string, Attribute> attributes = 12;

	// optional field.
	// hash of all chunk hashes. Not present for directories or uncommitted files
	SHA256 hash_of_hashes = 13;

	// An identifier to differentiate revisions of an inode
	string revision_tag = 14;

	// optional. list of user's permissions
	PermissionList permissions = 15;
}

message RelativePath {
	// inode ID of the parent directory
	string parent_id = 1;

	// base name of the file or directory
	string name = 2;
}

message FilePath {
	// The path where the directory will be created on the volume.
	oneof path {
		// full path name to the directory
		string full_path = 1;
		// parent inode_id and the directory name
		RelativePath relative_path = 2;
	}
}

message FileID {
	// File identifier - one of full path or file inode_id
	oneof id {
		string path = 1;
		string inode_id = 2;
	}
}

enum FileEvent {
	FILE_EVENT_UNSPECIFIED = 0;
	FILE_EVENT_CREATED = 1; // File or directory created
	FILE_EVENT_MODIFIED = 3; // The file or directory was modified - e.g. attributes changed, moved to a new location, file contents modified
	FILE_EVENT_MOVED = 4; // The file or directory was moved. The event corresponds with the desintaion inode
	FILE_EVENT_DELETED = 5; // The file or directory was deleted
}