// Generic common types that are not expected to change

syntax = "proto3";

option optimize_for = LITE_RUNTIME;
option swift_prefix = "CamAppControl";

package bmd.cam_app_control.v5;

message FrameRate {
  uint32 num = 1;
  uint32 den = 2;
}

message Shutter {
  uint32 num = 1;
  uint32 den = 2;
}

message PointF {
  float x = 1;
  float y = 2;
}

message TimeCode {
  // func secondsToHoursMinutesSeconds(_ seconds: Int) -> (Int, Int, Int) {
  //     return (seconds / 3600, (seconds % 3600) / 60, (seconds % 3600) % 60)
  // }
  uint32 seconds = 1;
  uint32 frame_count = 2;
}
