syntax = "proto3";

package com.blackmagicdesign.android.protobuf;

option java_package = "com.blackmagicdesign.android.protobuf";

message Point
{
    int32 x = 1;
    int32 y = 2;
}

message Resolution
{
    int32 width = 1;
    int32 height = 2;
}

message FrameRate
{
    int32 num = 1;
    int32 den = 2;
}

message AudioTrack
{
    string codec = 1;
    int32 channels = 2;
    int32 bit_depth = 3;
    int32 sample_rate = 4;
}

message VideoTrack
{
    string codec = 1;
    Resolution resolution = 2;
    FrameRate frame_rate = 3;
    uint32 frame_count = 4;
}

message CommonClipMetadata
{
    // use optional to always write default required field
    optional string manufacturer = 1;
    optional bool good_take = 2;
    optional string lens_type = 3;
    optional string reel = 4;
    optional string scene = 5;
    optional string color_space = 6;
    optional string lut_applied = 7;
    optional string take = 8;
    optional string gamma = 9;
    optional string anamorphic = 10;
    optional string lut_displayed = 11;
    optional bool offspeed_enabled = 12;
    optional string shot_type = 13;
    optional string take_type = 14;
}

message CommonFirstFrameMetadata
{
    // use optional to always write default required field
    optional string aperture = 1;
    optional float nd_filter = 2;
    optional int32 iso = 3;
    optional FrameRate sensor_rate = 4;
    optional string shutter_value = 5;
    optional int32 white_balance_kelvin = 6;
    optional int32 white_balance_tint = 7;
}

message FileSpecificClipMetadata
{
    float analog_gain = 1;
    int32 analog_gain_is_constant = 2;
    string anamorphic = 3;
    int32 anamorphic_enable = 4;
    uint32 codec_bitrate = 5;
    string codec_compression_ratio = 6;
    string camera_id = 7;
    string camera_number = 8;
    string camera_operator = 9;
    string camera_type = 10;
    string clip_number = 11;
    repeated float crop_origin = 12;
    repeated float crop_size = 13;
    string date_recorded = 14;
    string day_night = 15;
    string director = 16;
    string encoder_device_manufacturer = 17;
    string environment = 18;
    string filters = 19;
    string firmware_version = 20;
    string frameguide_aspect_ratio = 21;
    string frameguide_safe_area = 22;
    int32 gamut_compression_enable = 23;
    string good_take = 24;
    string lens_type = 25;
    string location = 26;
    string manufacturer = 27;
    int32 offspeed = 28;
    int32 ois_enable = 29;
    string production_name = 30;
    string reel_name = 31;
    int32 rotation = 32;
    repeated float safe_area = 33;
    string scene = 34;
    repeated float sensor_area_captured = 35;
    float sensor_line_time = 36;
    string shot_type = 37;
    string shutter_type = 38;
    string take = 39;
    string take_type = 40;
    string time_lapse_interval = 41;
    int32 viewing_bmdgen = 42;
    string viewing_gamma = 43;
    string viewing_gamut = 44;
    string original_codec = 45;
    Resolution original_resolution = 46;
}

message FileSpecificFirstFrameMetadata
{
    float analog_gain = 1;
    string aperture = 2;
    int32 as_shot_kelvin = 3;
    int32 as_shot_tint = 4;
    string distance = 5;
    float exposure = 6;
    string focal_length = 7;
    float internal_nd = 8;
    int32 iso = 9;
    repeated int32 sensor_rate = 10;
    string shutter_value = 11;
    int32 white_balance_kelvin = 12;
    int32 white_balance_tint = 13;
}

message VideoFileInfo
{
    string _schema = 1;
    string filename = 2;
    uint64 size_in_bytes = 3;
    string creation_date = 4;
    string start_timecode = 5;
    VideoTrack video = 6;
    repeated AudioTrack audio = 7;
    optional CommonClipMetadata common_clip_metadata = 8;
    optional CommonFirstFrameMetadata common_first_frame_metadata = 9;
    optional FileSpecificClipMetadata file_specific_clip_metadata = 10;
    optional FileSpecificFirstFrameMetadata file_specific_first_frame_metadata = 11;
    string codecs = 12;
}
