// Blackmagic Cam Application: Remote Control Protocol
// Version 4.0 (update `package` when bumping up version)
//
// This protocol is intended to be used over an already-established WebRTC Data Channel.
// Camera discovery is outside the scope of this protocol. We assume that basics such as protocol compatibility were
// already checked by other means such as Bonjour TXT records.

syntax = "proto3";

option optimize_for = LITE_RUNTIME; // iOS protobufs-lite runtime is 1.7M vs 8.2M for full
option swift_prefix = "CamAppControl";

package bmd.cam_app_control.v5;

import "camera_control.proto";
import "common.proto";
import "settings.proto";

//
// Initial handshake, should happen before any other messages are exchanged.
// Avoid adding redundant information that is already shared on the signaling protocol (e.g. slate name and proto version)
//

// Controller-only
message HelloRequest {
  AppInfo app_info = 1;
}

// Subordinate-only
message HelloResponse {
  AppInfo app_info = 1;
  repeated VideoCodec encoding_video_codecs = 2;
}

enum VideoCodec {
  VIDEO_CODEC_UNSPECIFIED = 0;
  VIDEO_CODEC_H264 = 1;
  VIDEO_CODEC_H265_MAIN = 2;
  VIDEO_CODEC_H265_MAIN_10 = 3;
  VIDEO_CODEC_H265_MAIN_422_10 = 4;
}

//
// Subordinate Properties:
// - Can be read by the Controller with ReadPropertyRequest
// - Can be written by the Controller with WritePropertyRequest (unless property is read-only)
// - Can be proactively sent by the Subordinate when they change with PropertyChangedEvent
//

// Controller-only
message ReadPropertyRequest {
  PropertyId property_id = 1;
}

// Subordinate-only
message ReadPropertyResponse {
  Property property = 1;
}

// Controller-only
// Not allowed when Subordinate is in "Monitor Only" mode.
message WritePropertyRequest {
  Property property = 1;
  bool override_confirm = 2; // Set to true when sending request again after receiving WRITE_PROPERTY_STATUS_REQUIRES_CONFIRM
}

// Subordinate-only
message WritePropertyResponse {
  WritePropertyStatus status = 1;
  optional Property requested_value = 2; // Value received in WritePropertyRequest. Only set when status != WRITE_PROPERTY_STATUS_OK.

  // Translated to Controller language. Set when status == WRITE_PROPERTY_STATUS_REQUIRES_CONFIRM
  optional string confirmation_message = 3;

  // Actual value of the property. Only set when status != WRITE_PROPERTY_STATUS_OK.
  optional Property current_value = 4;
}

enum WritePropertyStatus {
  WRITE_PROPERTY_STATUS_UNSPECIFIED = 0;
  WRITE_PROPERTY_STATUS_OK = 1;
  WRITE_PROPERTY_STATUS_ERROR_INVALID_VALUE = 2;
  WRITE_PROPERTY_STATUS_ERROR_READ_ONLY = 3;
  WRITE_PROPERTY_STATUS_WARNING = 4; // Writing the exact value requested was not possible, check returned property
  WRITE_PROPERTY_STATUS_REQUIRES_CONFIRM = 5; // Requires user confirmation before applying changes.
}

// Subordinate-only
message PropertyChangedEvent {
  Property property = 1;
}

//
// Preview Control
//

// Controller-only
message StartPreviewRequest {
  VideoCodec video_codec = 1; // Chosen from Subordinate's HelloResponse.encoding_video_codecs
  optional FrameRate frame_rate = 2;
  uint32 audio_num_channels_to_stream = 3;
}

// Subordinate-only
message StartPreviewResponse {
  StartPreviewStatus status = 1;
}

enum StartPreviewStatus {
  START_PREVIEW_STATUS_UNSPECIFIED = 0;
  START_PREVIEW_STATUS_OKAY = 1;
  START_PREVIEW_STATUS_FAILED = 2;
}

// Controller-only
message StopPreviewRequest {}

// Subordinate-only
message StopPreviewResponse {}

//
// Recording Control
//

// Controller-only
// Not allowed when Subordinate is in "Monitor Only" mode.
message StartRecordingRequest {
  bool dim_screen = 1; // Request to dim Subordinate screen to save battery and reduce heat while recording
}

// Subordinate-only
message StartRecordingResponse {
  StartRecordingStatus status = 1;
}

enum StartRecordingStatus {
  START_RECORDING_STATUS_UNSPECIFIED = 0;
  START_RECORDING_STATUS_OKAY = 1;
  START_RECORDING_STATUS_FAILED = 2;
  START_RECORDING_STATUS_FAILED_STORAGE_IS_FULL = 3;
}

// Controller-only
// Not allowed when Subordinate is in "Monitor Only" mode.
message StopRecordingRequest {}

// Subordinate-only
message StopRecordingResponse {
  StopRecordingStatus status = 1;
}

enum StopRecordingStatus {
  STOP_RECORDING_STATUS_UNSPECIFIED = 0;
  STOP_RECORDING_STATUS_OKAY = 1;
  STOP_RECORDING_STATUS_FAILED = 2;
}

// Controller-only
// Not allowed when Subordinate is in "Monitor Only" mode.
message PauseRecordingRequest {}

// Subordinate-only
message PauseRecordingResponse {
  PauseRecordingStatus status = 1;
}

enum PauseRecordingStatus {
  PAUSE_RECORDING_STATUS_UNSPECIFIED = 0;
  PAUSE_RECORDING_STATUS_OKAY = 1;
  PAUSE_RECORDING_STATUS_FAILED = 2;
}

// Subordinate-only: Note that RecordingStoppedEvent may also contain the reason RECORDING_STOPPED_REASON_DROPPED_FRAMES
message FramesDroppedEvent {
  optional uint64 count = 1;
}

//
// Settings Control
//

// Controller-only: Request to start editing settings, which will block editing settings on the Subordinate.
// Not allowed when Subordinate is in "Monitor Only" mode.
message StartSettingsEditRequest {}

// Subordinate-only: Describes the settings available, current and default values.
message StartSettingsEditResponse {
  StartSettingsEditStatus status = 1;
  AvailableSettings available_settings = 2;
}

enum StartSettingsEditStatus {
  START_SETTINGS_EDIT_STATUS_UNSPECIFIED = 0;
  START_SETTINGS_EDIT_STATUS_OKAY = 1;
  START_SETTINGS_EDIT_STATUS_REJECTED = 2;
}

// Controller-only: Sends list of modified settings
// Not allowed when Subordinate is in "Monitor Only" mode.
message WriteSettingsRequest {
  repeated WriteSetting settings = 1;
  bool is_done_editing = 2;
}

// Subordinate-only
message WriteSettingsResponse {
  repeated WriteSettingStatus status = 1;
  optional string confirmation_message = 2; // Translated to Controller language. Set when status == WRITE_SETTING_STATUS_REQUIRES_CONFIRM
}

enum WriteSettingStatus {
  WRITE_SETTING_STATUS_UNSPECIFIED = 0;
  WRITE_SETTING_STATUS_OKAY = 1;
  WRITE_SETTING_STATUS_FAILED = 2;
  WRITE_SETTING_STATUS_REQUIRES_CONFIRM = 3; // Requires user confirmation before applying changes. Only used for Android-Android connections. Android auto-confirms when connected with an iOS
  WRITE_SETTING_STATUS_WAITING_CONFIRM = 4; // Used when trying to write settings and an expected ConfirmWriteSettingsRequest was not received yet. Only used for Android-Android connections. Android auto-confirms when connected with an iOS
}

// Controller-only. Use when WriteSettingsResponse with status == WRITE_SETTING_STATUS_REQUIRES_CONFIRM was received.
message ConfirmWriteSettingsRequest {
  bool yes = 1;
}

// Subordinate-only
message ConfirmWriteSettingsResponse {
  // Optional: Subordinate may want to update the available settings
  repeated AvailableSettings available_settings = 1;
}

// Subordinate-only
// Used by the subordinate to notify the Controller that it needs to re-populate the settings because they have
// changed while editing.
message SettingsChangedEvent {
  AvailableSettings available_settings = 1;
}

//
// Flow Control and Misc
//

// This message should be sent before disconnecting. It helps shorten the time it takes the other end to detect that
// the connection is terminated (in particular with WebRTC Data Channel).
message DisconnectEvent {}

// Controller-only. Used to request the Controller to identify the camera, for example by blinking the screen.
message IdentifyCamRequest {}

// Subordinate-only
message IdentifyCamResponse {}

message HeartBeatRequest {}

message HeartBeatResponse {}

// WebRTC SDP offers can be sent to open additional Audio/Video channels
message WebRtcSdpRequest {
  string data = 1;
}

// WebRTC SDP response can be sent to open additional Audio/Video channels
message WebRtcSdpResponse {
  string data = 1;
}

// Subordinate-only
message ErrorEvent {
  ErrorEventType error_type = 1;
}

enum ErrorEventType {
  ERROR_EVENT_TYPE_UNSPECIFIED = 0;
  ERROR_EVENT_TYPE_TEMP_TOO_HIGH = 1; // Temperature too high
  ERROR_EVENT_TYPE_STORAGE_FULL = 2; // Storage full
  ERROR_EVENT_TYPE_BATTERY_LOW = 3; // Battery Low
  ERROR_EVENT_TYPE_EXT_DRIVE_DISCONNECTED = 4; // External hard drive has disconnect
  ERROR_EVENT_TYPE_UPLOAD_FAILED = 5; // Upload failed
  ERROR_EVENT_TYPE_AUDIO_SOURCE_UNAVAILABLE = 6; // Audio source unavailable
  ERROR_EVENT_TYPE_RECORDING_STOPPED = 7; // Recording stopped: No reason specified
  ERROR_EVENT_TYPE_RECORDING_STOPPED_APP_LOST_FOCUS = 8; // Recording stopped: App lost focus
  ERROR_EVENT_TYPE_RECORDING_STOPPED_DROPPED_FRAMES = 9; // Recording stopped: Dropped frames
  ERROR_EVENT_TYPE_RECORDING_STOPPED_STORAGE_FULL = 10; // Recording stopped: Storage is full
  ERROR_EVENT_TYPE_RECORDING_STOPPED_REQUIRES_EXTERNAL_STORAGE = 11; // Recording stop: Apple ProRes Raw Requires Recording to External Storage
}

//
// Main messages
//

// Controller-only
message ControllerMessage {
  uint64 message_id = 1; // Use incremental, non-zero values
  optional uint64 subordinate_message_id = 2; // Referencing SubordinateMessage::message_id
  oneof message {
    HelloRequest hello_request = 3;
    DisconnectEvent disconnect_event = 4;
    ReadPropertyRequest read_property_request = 5;
    WritePropertyRequest write_property_request = 6;
    StartPreviewRequest start_preview_request = 7;
    StopPreviewRequest stop_preview_request = 8;
    StartRecordingRequest start_recording_request = 9;
    StopRecordingRequest stop_recording_request = 10;
    HeartBeatRequest heart_beat_request = 11;
    HeartBeatResponse heart_beat_response = 12;
    WebRtcSdpRequest webrtc_sdp_request = 13;
    WebRtcSdpResponse webrtc_sdp_response = 14;
    StartSettingsEditRequest start_settings_edit_request = 15;
    IdentifyCamRequest identify_request = 16;
    WriteSettingsRequest write_settings_request = 17;
    ConfirmWriteSettingsRequest confirm_write_settings_request = 18;    // Only used for Android-Android connections. Android auto-confirms when connected with an iOS
    PauseRecordingRequest pause_recording_request = 19; // toggle pause state
  }
}

// Subordinate-only
message SubordinateMessage {
  uint64 message_id = 1; // Use incremental, non-zero values
  optional uint64 controller_message_id = 2; // Referencing ControllerMessage::message_id
  oneof message {
    HelloResponse hello_response = 3;
    DisconnectEvent disconnect_event = 4;
    ErrorEvent error_event = 5;
    ReadPropertyResponse read_property_response = 6;
    WritePropertyResponse write_property_response = 7;
    PropertyChangedEvent property_changed_event = 8;
    StartPreviewResponse start_preview_response = 9;
    StopPreviewResponse stop_preview_response = 10;
    StartRecordingResponse start_recording_response = 11;
    StopRecordingResponse stop_recording_response = 12;
    HeartBeatRequest heart_beat_request = 13;
    HeartBeatResponse heart_beat_response = 14;
    WebRtcSdpRequest webrtc_sdp_request = 15;
    WebRtcSdpResponse webrtc_sdp_response = 16;
    StartSettingsEditResponse start_settings_edit_response = 17;
    FramesDroppedEvent frames_dropped_event = 18;
    IdentifyCamResponse identify_response = 19;
    WriteSettingsResponse write_settings_response = 20;
    ConfirmWriteSettingsResponse confirm_write_settings_response = 21;  // Only used for Android-Android connections. Android auto-confirms when connected with an iOS
    SettingsChangedEvent settings_changed_event = 22;
    PauseRecordingResponse pause_recording_response = 23;
  }
}

// Controller-only: Top-level message to serialize and send on the wire. Allows message aggregation.
message ControllerMessages {
  repeated ControllerMessage messages = 1;
}

// Subordinate-only: Top-level message to serialize and send on the wire. Allows message aggregation.
message SubordinateMessages {
  repeated SubordinateMessage messages = 1;
}
